apps/cms/urls.py
from django.urls import path
from . import views, course_views, staff_views

app_name = 'cms'

urlpatterns = [
    path('index/', views.index_view, name='index'),
    path('write_news/', views.WriteNewsView.as_view(), name='write_news'),
    path('edit_news/', views.EditNewsView.as_view(), name='edit_news'),
    path('del_news/', views.del_news, name='edit_news'),
    path('news_list/', views.NewsListView.as_view(), name='news_list'),
    path('news_category/', views.news_category, name='news_category'),
    path('add_category/', views.add_news_category, name='add_category'),
    path('edit_category/', views.edit_news_category, name='edit_category'),
    path('del_category/', views.del_news_category, name='del_category'),
    path('upload_file/', views.upload_file, name='upload_file'),
    path('qntoken/', views.qntoekn, name='qn_token'),
    path('banners/', views.news_banners, name='news_banners'),
    path('add_banner/', views.add_banner, name='add_banner'),
    path('del_banner/', views.del_banner, name='del_banner'),
    path('edit_banner/', views.edit_banner, name='edit_banner'),
    path('banner_list/', views.banner_list, name='banner_list'),

]
urlpatterns += [
    path('course/', course_views.PubCourse.as_view(), name='pub_course'),
]

urlpatterns += {
    path('staffs/', staff_views.index, name='staffs'),
    path('add_staff/', staff_views.AddStaffView.as_view(), name='add_staff'),
}

apps/news/urls.py
from django.urls import path
from . import views
app_name = 'news'
urlpatterns = [
    path('<int:news_id>/', views.news_detail, name="news_detail"),
    path('list/', views.news_list, name="newses_list"),
    path('add_comment/', views.add_news_comment, name="add_comment"),
]

apps/xfzauth/urls.py
from django.urls import path
from . import views

app_name = 'xfzauth'
urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('img_captcha/', views.img_captcha, name='img_captcha'),
    path('sms_captcha/', views.sms_captcha, name='sms_captcha'),
    path('cached/', views.cache_test, name='cache_test'),
    path('register/', views.register, name='register'),
]

xfz/urls.py
from django.contrib import admin
from django.urls import path, include
from apps.news import views as news_views
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('', news_views.index, name='index'),
    # path('search/', news_views.search, name='search'),
    path('search/', include('haystack.urls')),
    path('news/', include('apps.news.urls')),
    path('cms/', include('apps.cms.urls')),
    path('account/', include('apps.xfzauth.urls')),
    path('course/', include('apps.course.urls')),
    path('payinfo/', include('apps.payinfo.urls')),
    path('ueditor/', include('apps.ueditor.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns.append(path("__debug__/", include(debug_toolbar.urls)))

apps/cms/models.py
from django.db import models

apps/news/models.py
from django.db import models


# Create your models here.
class NewsCategory(models.Model):
    name = models.CharField(max_length=10)


class News(models.Model):
    title = models.CharField(max_length=200)
    desc = models.CharField(max_length=200)
    thumbnail = models.URLField()
    content = models.TextField()
    pub_time = models.DateTimeField(auto_now_add=True)
    category = models.ForeignKey('NewsCategory', on_delete=models.SET_NULL, null=True)
    author = models.ForeignKey('xfzauth.User', on_delete=models.SET_NULL, null=True)

    class Meta:
        ordering = ['-pub_time']


class Comment(models.Model):
    content = models.TextField()
    pub_time = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey('xfzauth.User', on_delete=models.CASCADE)
    news = models.ForeignKey('News', on_delete=models.CASCADE, related_name='comments')

    class Meta:
        ordering = ['-pub_time']


class Banner(models.Model):
    priority = models.IntegerField(default=0)
    image_url = models.URLField()
    link_to = models.URLField()
    pub_time = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-priority']

apps/cms/forms.py
from django import forms
from apps.forms import FormsMixin
from apps.news.models import News, Banner
from apps.course.models import Course


class NewsEditForm(forms.Form):
    pk = forms.IntegerField(error_messages={'required': '必须传入分类的id'})
    name = forms.CharField(max_length=100)


class WriteNewsForm(forms.ModelForm, FormsMixin):
    category = forms.IntegerField()

    class Meta:
        model = News
        exclude = ['category', 'author', 'pub_time']

class EditNewsForm(forms.ModelForm, FormsMixin):
    pk = forms.IntegerField()
    category = forms.IntegerField()
    class Meta:
        model = News
        exclude = ['category', 'author', 'pub_time']


class BannerForm(forms.ModelForm, FormsMixin):
    class Meta:
        model = Banner
        fields = ['link_to', 'image_url', 'priority']


class EditBannerForm(forms.ModelForm, FormsMixin):
    pk = forms.IntegerField()

    class Meta:
        model = Banner
        fields = ['link_to', 'image_url', 'priority']


class CourseForm(forms.ModelForm, FormsMixin):
    category_id = forms.IntegerField()
    teacher_id = forms.IntegerField()

    class Meta:
        model = Course
        exclude = ['category', 'teacher', 'pub_time']

apps/cms/views.py
from django.shortcuts import render
from django.views.generic import View
from django.contrib.admin.views.decorators import staff_member_required
from django.views.decorators.http import require_POST, require_GET
from apps.news.models import NewsCategory, News, Banner
from utils import restful
from .forms import NewsEditForm, BannerForm, EditBannerForm
from apps.news.serializers import BannerSerializer
from django.core.paginator import Paginator
from django.conf import settings
from urllib import parse
import os
import qiniu
from django.conf import settings
from apps.cms.forms import WriteNewsForm, EditNewsForm
from datetime import datetime
from django.utils.timezone import make_aware
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import permission_required


@staff_member_required()
def index_view(request):
    return render(request, 'cms/index.html')


@method_decorator(permission_required(perm='news.add_news', login_url='/'), name='dispatch')
class WriteNewsView(View):
    def get(self, request):
        categories = NewsCategory.objects.all()
        context = {
            'categories': categories
        }
        return render(request, 'cms/write_news.html', context=context)

    def post(self, request):
        form = WriteNewsForm(request.POST)
        if form.is_valid():
            title = form.cleaned_data.get('title')
            desc = form.cleaned_data.get('desc')
            thumbnail = form.cleaned_data.get('thumbnail')
            content = form.cleaned_data.get('content')
            category_id = form.cleaned_data.get('category')
            category = NewsCategory.objects.get(pk=category_id)

            print('*' * 30)
            print(content)

            News.objects.create(title=title, desc=desc, thumbnail=thumbnail, content=content, category=category,
                                author=request.user)
            return restful.ok()
        else:
            return restful.paramserror(message=form.get_errors())


@method_decorator(permission_required(perm='news.change_news', login_url='/'), name='dispatch')
class EditNewsView(View):
    def get(self, request):
        news_id = request.GET.get('news_id')
        news = News.objects.get(pk=news_id)
        categories = NewsCategory.objects.all()
        context = {
            'news': news,
            'categories': categories,
        }
        return render(request, 'cms/write_news.html', context=context)

    def post(self, request):
        form = EditNewsForm(request.POST)
        if form.is_valid():
            title = form.cleaned_data.get('title')
            desc = form.cleaned_data.get('desc')
            thumbnail = form.cleaned_data.get('thumbnail')
            content = form.cleaned_data.get('content')
            category_id = form.cleaned_data.get('category')
            category = NewsCategory.objects.get(pk=category_id)
            pk = form.cleaned_data.get('pk')
            news = News.objects.filter(pk=pk).update(title=title, desc=desc, thumbnail=thumbnail, content=content,
                                                     category=category)
            return restful.ok()
        else:
            return restful.paramserror(message=form.get_errors())


@require_POST
@permission_required(perm='news.delete_news', login_url='/')
def del_news(request):
    news_id = request.POST.get('news_id')
    News.objects.filter(pk=news_id).delete()
    return restful.ok()


@require_GET
@permission_required(perm='news.change_banner', login_url='/')
def news_banners(request):
    return render(request, 'cms/banners.html')


@require_POST
@permission_required(perm='news.add_banner', login_url='/')
def add_banner(request):
    form = BannerForm(request.POST)
    if form.is_valid():
        priority = form.cleaned_data.get('priority')
        image_url = form.cleaned_data.get('image_url')
        link_to = form.cleaned_data.get('link_to')
        banner = Banner.objects.create(priority=priority, image_url=image_url, link_to=link_to)
        print(banner)
        return restful.result(data={'banner_id': banner.pk})
    else:
        return restful.paramserror(message=form.get_errors())


@permission_required(perm='news.change_banner', login_url='/')
def banner_list(request):
    banners = Banner.objects.all()
    serializer = BannerSerializer(banners, many=True)
    return restful.result(data=serializer.data)


@permission_required(perm='news.delete_banner', login_url='/')
def del_banner(request):
    banner_id = request.POST.get('banner_id')
    Banner.objects.filter(pk=banner_id).delete()
    return restful.ok()


@permission_required(perm='news.change_banner', login_url='/')
def edit_banner(request):
    form = EditBannerForm(request.POST)
    if form.is_valid():
        banner_id = form.cleaned_data.get('pk')
        link_to = form.cleaned_data.get('link_to')
        image_url = form.cleaned_data.get('image_url')
        priority = form.cleaned_data.get('priority')
        Banner.objects.filter(pk=banner_id).update(link_to=link_to, image_url=image_url, priority=priority)
        return restful.ok()
    else:
        return restful.paramserror(message=form.get_errors())


@require_GET
@permission_required(perm='category.change_coursecategory', login_url='/')
def news_category(request):
    categories = NewsCategory.objects.all()
    context = {
        'categories': categories
    }
    return render(request, 'cms/news_category.html', context=context)


@require_POST
@permission_required(perm='category.add_coursecategory', login_url='/')
def add_news_category(request):
    name = request.POST.get('name')
    exists = NewsCategory.objects.filter(name=name).exists()
    if not exists:
        NewsCategory.objects.create(name=name)
        return restful.ok()
    else:
        return restful.paramserror(message='该分类已经存在')


@require_POST
@permission_required(perm='category.change_coursecategory', login_url='/')
def edit_news_category(request):
    form = NewsEditForm(request.POST)
    if form.is_valid():
        pk = form.cleaned_data.get('pk')
        name = form.cleaned_data.get('name')
        try:
            NewsCategory.objects.filter(pk=pk).update(name=name)
            return restful.ok()
        except:
            return restful.paramserror('分类不存在')
    else:
        restful.paramserror('分类参数异常')


@require_POST
@permission_required(perm='category.delete_coursecategory', login_url='/')
def del_news_category(request):
    pk = request.POST.get('pk')
    if pk:
        try:
            NewsCategory.objects.filter(pk=pk).delete()
            return restful.ok()
        except:
            return restful.paramserror('分类不存在')
    else:
        return restful.paramserror('分类参数异常')


@require_POST
@staff_member_required()
def upload_file(request):
    file = request.FILES.get('file')
    name = file.name
    with open(os.path.join(settings.MEDIA_ROOT, name), 'wb') as fp:
        for chunk in file.chunks():
            fp.write(chunk)
    url = request.build_absolute_uri(settings.MEDIA_URL + name)
    return restful.result(data={'url': url})


# 七牛token获取
@require_GET
@staff_member_required()
def qntoekn(request):
    access_key = settings.QINIU_ACCESS_KEY
    secret_key = settings.QINIU_SECRET_KEY
    q = qiniu.Auth(access_key, secret_key)
    bucket_name = settings.QINIU_BUCKET_NAME
    token = q.upload_token(bucket_name)
    return restful.result(data={'token': token})


@method_decorator(permission_required(perm='change_news', login_url='/'), name='dispatch')
class NewsListView(View):
    def get(self, request):
        page = int(request.GET.get('p', 1))
        start = request.GET.get('start')
        end = request.GET.get('end')
        title = request.GET.get('title')
        category_id = int(request.GET.get('category', 0) or 0)

        newses = News.objects.select_related('author', 'category')
        if start or end:
            if start:
                start_date = datetime.strptime(start, '%Y/%m/%d')
            else:
                start_date = datetime(year=2019, month=6, day=1)

            if end:
                end_date = datetime.strptime(end, '%Y/%m/%d')
            else:
                end_date = datetime.today()
            newses = newses.filter(pub_time__range=(make_aware(start_date), make_aware(end_date)))

        if title:
            newses = newses.filter(title__icontains=title)

        if category_id:
            newses = newses.filter(category=category_id)

        paginator = Paginator(newses, 2)
        page_obj = paginator.page(page)
        categories = NewsCategory.objects.all()
        context_data = self.get_pagination_data(paginator, page_obj)
        context = {
            'newses': page_obj.object_list,
            'categories': categories,
            'page_obj': page_obj,
            'paginator': paginator,
            'start': start,
            'end': end,
            'title': title,
            'category_id': category_id,
            'url_query': '&' + parse.urlencode({
                'start': start or '',
                'end': end or '',
                'title': title or '',
                'category': category_id or ''
            })
        }
        context.update(context_data)
        return render(request, 'cms/news_list.html', context=context)

    def get_pagination_data(self, paginator, page_obj, around_count=2):
        current_page = page_obj.number
        num_pages = paginator.num_pages

        left_has_more = False
        right_has_more = False

        if current_page <= around_count + 2:
            left_pages = range(1, current_page)
        else:
            left_has_more = True
            left_pages = range(current_page - around_count, current_page)

        if current_page >= num_pages - around_count - 1:
            right_pages = range(current_page + 1, num_pages + 1)
        else:
            right_has_more = True
            right_pages = range(current_page + 1, current_page + around_count + 1)

front/templates/cms/base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="csrftoken" content="{{ csrf_token }}">
    <title>{% block title %}{% endblock %} | jc测试管理系统</title>
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <link rel="stylesheet" href="{% static 'adminlte/bower_components/bootstrap/dist/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'adminlte/bower_components/font-awesome/css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'adminlte/dist/css/AdminLTE.min.css' %}">
    <link rel="stylesheet" href="{% static 'adminlte/dist/css/skins/_all-skins.min.css' %}">
    <link rel="stylesheet" href="{% static 'adminlte/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css' %}">
    <link rel="stylesheet" href="{% static 'sweetalert/sweetalert.css' %}">
    <script src="{% static 'adminlte/bower_components/jquery/dist/jquery.min.js' %}"></script>
    <script src="{% static 'adminlte/bower_components/bootstrap/dist/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'adminlte/dist/js/adminlte.min.js' %}"></script>
    <script src="{% static 'sweetalert/sweetalert.min.js' %}"></script>
    <script src="{% static 'js/xfzajax.min.js' %}"></script>
    <script src="{% static 'js/xfzalert.min.js' %}"></script>
    <script src="{% static 'js/message.min.js' %}"></script>
    {% block head %}{% endblock %}
</head>
<body class="hold-transition skin-blue sidebar-mini">
<div class="wrapper">
    <header class="main-header">
        <!-- Logo -->
        <a href="/" class="logo">
            <!-- mini logo for sidebar mini 50x50 pixels -->
            <span class="logo-mini"><b>CMS</b></span>
            <!-- logo for regular state and mobile devices -->
            <span class="logo-lg">jc测试后台管理系统</span>
        </a>
        <!-- Header Navbar: style can be found in header.less -->
        <nav class="navbar navbar-static-top">
            <!-- Sidebar toggle button-->
            <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
                <span class="sr-only">Toggle navigation</span>
            </a>

            <div class="navbar-custom-menu">
                <ul class="nav navbar-nav">
                    <li class="dropdown user user-menu">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <img src="http://edu-image.nosdn.127.net/4B9BE586B1F982317B930C2C2E6F702D.png"
                                 class="user-image" alt="User Image">
                            <span class="hidden-xs">黄勇</span>
                        </a>
                        <ul class="dropdown-menu">
                            <!-- User image -->
                            <li class="user-header">
                                <img src="http://edu-image.nosdn.127.net/4B9BE586B1F982317B930C2C2E6F702D.png"
                                     class="img-circle" alt="User Image">
                                <p>
                                    黄勇
                                    <small>Python web开发工程师</small>
                                </p>
                            </li>
                            <!-- Menu Footer-->
                            <li class="user-footer">
                                <div class="pull-left">
                                    <a href="#" class="btn btn-default btn-flat">个人中心</a>
                                </div>
                                <div class="pull-right">
                                    <a href="#" class="btn btn-default btn-flat">退出登录</a>
                                </div>
                            </li>
                        </ul>
                    </li>
                </ul>
            </div>
        </nav>
    </header>
    <aside class="main-sidebar">
        <!-- sidebar: style can be found in sidebar.less -->
        <section class="sidebar">
            <form action="#" method="get" class="sidebar-form">
                <div class="input-group">
                    <input type="text" name="q" class="form-control" placeholder="首页">
                    <span class="input-group-btn">
                <button type="submit" name="search" id="search-btn" class="btn btn-flat"><i class="fa fa-search"></i>
                </button>
          </span>
                </div>
            </form>
            <!-- /.search form -->
            <!-- sidebar menu: : style can be found in sidebar.less -->
            <ul class="sidebar-menu" data-widget="tree">
                <li class="active">
                    <a href="{% url 'cms:index' %}">
                        <i class="fa fa-home"></i>
                        <span>首页</span>
                    </a>
                </li>
                {% if perms.news.change_news %}
                    <li class="header">
                        新闻管理
                    </li>

                    <li>
                        <a href="{% url 'cms:news_list' %}">
                            <i class="fa fa-list"></i>
                            <span>新闻列表</span>
                        </a>
                    </li>

                    <li>
                        <a href="{% url 'cms:write_news' %}">
                            <i class="fa fa-edit"></i>
                            <span>发布新闻</span>
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'cms:news_category' %}">
                            <i class="fa fa-tag"></i>
                            <span>新闻分类</span>
                        </a>
                    </li>

                    <li>
                        <a href="{% url 'cms:news_banners' %}">
                            <i class="fa fa-window-restore"></i>
                            <span>轮播banner</span>
                        </a>
                    </li>

                {% endif %}

                {% if perms.course.change_newscategory %}
                    <li class="header">课程管理</li>
                    <li>
                        <a href="{% url 'cms:pub_course' %}">
                            <i class="fa fa-tv"></i>
                            <span>发布课程</span>
                        </a>
                    </li>
                {% endif %}

                {% if user.is_superuser %}
                    <li class="header">员工管理</li>
                    <li>
                        <a href="{% url 'cms:staffs' %}">
                            <i class="fa fa-group"></i>
                            <span>员工管理</span>
                        </a>
                    </li>
                {% endif %}


            </ul>
        </section>
    </aside>

    <div class="content-wrapper">
        <section class="content-header">
            {% block content-header %}{% endblock %}
        </section>
        <section class="content">
            <section class="content">
                {% block content %}{% endblock %}
            </section>
        </section>
    </div>

    <footer class="main-footer">
        <strong>小饭桌</strong>后台管理系统
    </footer>
</div>
</body>
</html>

front/templates/cms/index.html
{% extends 'cms/base.html' %}
{% block title %}
    首页
{% endblock %}

front/templates/cms/news_list.html
{% extends 'cms/base.html' %}
{% load news_filters %}
{% block title %}
    新闻列表
{% endblock %}

{% block head %}
    <style>
        .left-group {
            margin-left: 20px;
        }
    </style>
    <link rel="stylesheet"
          href="{% static 'adminlte/bower_components/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css' %}">
    <script src="{% static 'adminlte/bower_components/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js' %}"></script>
    <script src="{% static 'adminlte/bower_components/bootstrap-datepicker/dist/locales/bootstrap-datepicker.zh-CN.min.js' %}"></script>
    <script src="{% static 'js/news_list.min.js' %}"></script>
{% endblock %}

{% block content-header %}
    <h1>新闻管理</h1>
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-12">
            <div class="box box-primary">
                <div class="box-header">
                    <form action="" class="form-inline">
                        <div class="form-group left-group">
                            <label for="">时间：</label>
                            {% if start %}
                                <input type="text" class="form-control" name="start" value="{{ start }}"
                                       placeholder="起始时间" id="start-picker" autocomplete="off">
                            {% else %}
                                <input type="text" class="form-control" name="start"
                                       placeholder="起始时间" id="start-picker" autocomplete="off">
                            {% endif %}
                            <span>-</span>
                            {% if end %}
                                <input type="text" class="form-control" name="end" value="{{ end }}" placeholder="结束时间"
                                       id="end-picker"
                                       autocomplete="off">
                            {% else %}
                                <input type="text" class="form-control" name="end" placeholder="结束时间"
                                       id="end-picker"
                                       autocomplete="off">
                            {% endif %}
                        </div>
                        <div class="form-group left-group">
                            <label for="title-input">标题</label>
                            {% if title %}
                                <input type="text" class="form-control" value="{{ title }}" name="title"
                                       id="title-input" placeholder="关键字">
                            {% else %}
                                <input type="text" class="form-control" name="title" id="title-input" placeholder="关键字">
                            {% endif %}
                        </div>
                        <div class="form-group left-group">
                            <label for="">分类</label>
                            <select name="category" id="" class="form-control left-group">
                                {% if category_id == 0 %}
                                    <option value="0" selected>所有分类</option>
                                {% else %}
                                    <option value="0">所有分类</option>
                                {% endif %}

                                {% for category in categories %}
                                    {% if category_id == category.pk %}
                                        <option value="{{ category.pk }}" selected>{{ category.name }}</option>
                                    {% else %}
                                        <option value="{{ category.pk }}">{{ category.name }}</option>
                                    {% endif %}

                                {% endfor %}
                            </select>
                        </div>
                        <div class="form-group left-group">
                            <button class="btn btn-primary">查询</button>
                        </div>
                        <div class="form-group left-group">
                            <a href="{% url 'cms:news_list' %}">清除查询</a>
                        </div>
                    </form>
                </div>
                <div class="box-body">
                    <table class="table table-bordered">
                        <thead>
                        <tr>
                            <td>标题</td>
                            <td>分类</td>
                            <td>发布时间</td>
                            <td>作者</td>
                            <td>操作</td>
                        </tr>
                        </thead>
                        <tbody>



                        {% for news in newses %}
                            <tr>
                                <td><a target="_blank"
                                       href="{% url 'news:news_detail'  news_id=news.pk %}">{{ news.title }}</a></td>
                                <td>{{ news.category.name }}</td>
                                <td>{{ news.pub_time | time_format}}</td>
                                <td>{{ news.author.username }}</td>
                                <td>
                                    <a href="{% url 'cms:edit_news'%}?news_id={{ news.pk }}" class="btn btn-primary btn-xs">编辑</a>
                                    <button class="btn btn-danger btn-xs" id="del-btn" data-news-id="{{ news.pk }}" >删除</button>
                                </td>
                            </tr>
                        {% endfor %}

                        </tbody>
                    </table>
                </div>
                <div class="box-footer">
                    <p class="pull-left">{{ current_page }} / {{ num_pages }}页</p>
                    <ul class="pagination pull-right">
                        {#上一页#}
                        {% if page_obj.has_previous %}
                            <li><a href="{% url 'cms:news_list' %}?p={{ page_obj.previous_page_number }}{{ url_query }}">上一页</a>
                            </li>
                        {% else %}
                            <li class="disabled"><a href="javascript:void(0);">上一页</a></li>
                        {% endif %}

                        {# 是否需要出现三个点 #}
                        {% if left_has_more %}
                            <li><a href="?p=1">1</a></li>
                            <li><a href="javascript:void(0);">...</a></li>
                        {% endif %}

                        {# 左边的页码 #}
                        {% for left_page in left_pages %}
                            <li><a href="{% url 'cms:news_list' %}?p={{ left_page }}{{ url_query }}">{{ left_page }}</a>
                            </li>
                        {% endfor %}

                        {# 当前的页面 #}
                        <li class="active"><a
                                href="{% url 'cms:news_list' %}?p=
                                        {{ current_page }}{{ url_query }}">{{ current_page }}</a></li>

                        {# 右边的页码 #}
                        {% for right_page in right_pages %}
                            <li><a href="{% url 'cms:news_list' %}?p={{ right_page }}{{ url_query }}">{{ right_page }}</a></li>
                        {% endfor %}

                        {# 用来控制右边三个点 #}
                        {% if right_has_more %}
                            <li><a href="javascript:void(0);">...</a></li>
                            <li><a href="{% url 'cms:news_list' %}?p={{ num_pages }}{{ url_query }}">{{ num_pages }}</a>
                            </li>
                        {% endif %}

                        {#下一页#}
                        {% if page_obj.has_next %}
                            <li><a href="{% url 'cms:news_list' %}?p={{ page_obj.next_page_number }}{{ url_query }}">下一页</a></li>
                        {% else %}
                            <li class="disabled"><a href="javascript:void(0);">下一页</a></li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </div>
    </div>

{% endblock %}