apps/payinfo/urls.py
from django.urls import path
from . import views
app_name = 'payInfo'
urlpatterns = [
    path('', views.payinfo_index, name="index"),
    path('payinfo_order/', views.payinfo_order, name="payinfo_order"),
    path('notify_url/', views.notify_view, name="notify_view"),
    path('download/', views.download, name="download"),
]

xfz/urls.py
from django.contrib import admin
from django.urls import path, include
from apps.news import views as news_views
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('', news_views.index, name='index'),
    # path('search/', news_views.search, name='search'),
    path('search/', include('haystack.urls')),
    path('news/', include('apps.news.urls')),
    path('cms/', include('apps.cms.urls')),
    path('account/', include('apps.xfzauth.urls')),
    path('course/', include('apps.course.urls')),
    path('payinfo/', include('apps.payinfo.urls')),
    path('ueditor/', include('apps.ueditor.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns.append(path("__debug__/", include(debug_toolbar.urls)))

apps/payinfo/models.py
from django.db import models
from shortuuidfield import ShortUUIDField


# Create your models here.

class PayInfo(models.Model):
    title = models.CharField(max_length=100)
    profile = models.CharField(max_length=200)
    price = models.FloatField()
    path = models.FilePathField()


class PayInfoOrder(models.Model):
    uid = ShortUUIDField(primary_key=True)
    payinfo = models.ForeignKey('PayInfo', on_delete=models.DO_NOTHING)
    buyer = models.ForeignKey('xfzauth.User', on_delete=models.DO_NOTHING)
    amount = models.FloatField(default=0)
    pub_time = models.DateTimeField(auto_now_add=True)
    istype = models.SmallIntegerField(default=0)
    status = models.SmallIntegerField(default=1)

apps/payinfo/views.py
from django.shortcuts import render, reverse
from .models import PayInfo, PayInfoOrder
from apps.xfzauth.decorators import xfz_login_required
from utils import restful
from django.views.decorators.csrf import csrf_exempt
import os
from django.conf import settings
from django.http import Http404, FileResponse


def payinfo_index(request):
    payinfos = PayInfo.objects.all()
    context = {
        'payInfos': payinfos
    }
    return render(request, 'payinfo/payinfo.html', context=context)


@xfz_login_required
def payinfo_order(request):
    payinfo_id = request.GET.get('payinfo_id')
    payInfo = PayInfo.objects.get(pk=payinfo_id)
    order = PayInfoOrder.objects.create(payinfo=payInfo, buyer=request.user, amount=payInfo.price)
    context = {
        'goods': {
            'cover_url': 'http://xfz.cn/static/build/images/web-bp-pc.png',
            'title': payInfo.title,
            'price': payInfo.price,
        },
        'order': order,
        'notify_url': request.build_absolute_uri(reverse('payInfo:notify_view')),
        'return_url': request.build_absolute_uri(reverse('payInfo:index')),
    }

    return render(request, 'course/course_order.html', context=context)


@csrf_exempt
def notify_view(request):
    order_id = request.POST.get('order_id')
    PayInfoOrder.objects.filter(pk=order_id).update(status=2)
    return restful.ok()


@xfz_login_required
def download(request):
    payinfo_id = request.GET.get('payinfo_id')
    order = PayInfoOrder.objects.filter(payinfo_id=payinfo_id, buyer=request.user, status=2).first()
    if order:
        payinfo = order.payinfo
        path = payinfo.path
        fp = open(os.path.join(settings.MEDIA_ROOT, path), 'rb')
        response = FileResponse(fp)
        response['Content-Type'] = 'image/jpeg'
        response['Content-Disposition'] = 'attachment;filename="%s"' % path.split("/")[-1]
        return response
    else:
        return Http404

front/templates/payinfo/payinfo.html
{% extends 'base/front_base.html' %}

{% load payinfo_filters %}
{% block title %}
    企业服务
{% endblock %}
{% block header %}
    <link rel="stylesheet" href="{% static 'css/payinfo/payinfo.min.css' %}">
    <script src="{% static 'js/index.min.js' %}"></script>
{% endblock %}
{% block main %}

    <div class="main">
        <div class="wrapper">
            <div class="main-content-wrapper">
                <div class="advice-group">
                    <a href="#">
                        <img src="http://www.xfz.cn/static/build/images/web-venture-banner.png" alt="">
                    </a>
                </div>

                <ul class="document-list">
                    {% for payInfo in payInfos %}
                        <li>
                            {% with payInfo|is_buyed:user as buyed %}
                                {% if buyed %}
                                    <a href="{% url 'payInfo:download' %}?payinfo_id={{ payInfo.pk }}">
                                {% else %}
                                    <a href="{% url 'payInfo:payinfo_order' %}?payinfo_id={{ payInfo.pk }}">
                                {% endif %}

                            <div class="category-group"></div>
                            <div class="document-info">
                                <p class="document-title">{{ payInfo.title }}</p>
                                <p class="document-desc">{{ payInfo.profile }}</p>
                                {% if buyed %}
                                    <p class="document-price">点击下载</p>
                                {% else %}
                                    <p class="document-price">￥{{ payInfo.price }}</p>
                                {% endif %}

                            </div>
                            </a>
                            {% endwith %}
                        </li>
                    {% endfor %}
                </ul>

            </div>
            {% include 'common/sidebar.html' %}
        </div>
    </div>
{% endblock %}